[phases.setup]
nixPkgs = ["nodejs_20", "php84", "php84Packages.composer", "php84Extensions.pdo_pgsql", "php84Extensions.pgsql", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.tokenizer", "php84Extensions.dom", "php84Extensions.fileinfo"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
