[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.tokenizer", "php84Extensions.dom", "php84Extensions.fileinfo", "nodejs_20", "npm"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
